# Generated by Django 3.0.7 on 2020-06-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200622_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='descripton',
            new_name='description',
        ),
    ]
